sudo: required

services:
  - docker

before_install:
  - docker build -t docker-react  .
  - docker build -t docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-test npm run test 

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-east-1-573784929197
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  